name: Run CodeWeTrust Executive Report

on: workflow_dispatch

jobs:
  cwt-analysis:
    runs-on: ubuntu-20.04

    timeout-minutes: 55

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: SourceCodeToAnalyze
        fetch-depth: 0 # avoid shallow clone so that Git history analysis works

    - name: CodeWeTrust Executive Report Generator
      uses: Source-Code-Inspection-inc/CodeWeTrust-GitHubAction-ExecutiveReport@v0.5
      with:
        path: SourceCodeToAnalyze
        licenseKey: ${{ secrets.CWT_LICENSE_KEY }}
